# --- Build step
FROM node:alpine AS builder

WORKDIR /test-runner

COPY ./test/integration/package*.json ./
COPY ./scripts/wait-for-it.sh ./scripts/

RUN npm install --quiet --unsafe-perm

COPY ./test ./test/

FROM node:alpine

# Execution step
WORKDIR /test-runner

COPY --from=builder /test-runner ./

EXPOSE 4649
