version: '3'

networks:
  graphql-server-network:
    driver: bridge

services:
  graphql-server:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://db:27017/test-db
      - PORT=4000
    depends_on:
      - transpiler
      - db
    networks:
      - graphql-server-network
    command: ["/app/node_modules/.bin/nodemon", "dist/src/index.js"]

  transpiler:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - graphql-server-network
    command: ["/app/node_modules/.bin/tsc", "--watch"]

  db:
    image: 'mongo:3.6.6'
    ports:
      - '27017:27017'
    command: ["mongod", "--smallfiles", "--quiet", "--logpath=/dev/null"]
    networks:
      - graphql-server-network
